/*
 * File: app/view/Base.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Base', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'panel',
                id: 'homeView',
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        height: 192,
                        ui: 'light',
                        title: 'Wealth Management'
                    },
                    {
                        xtype: 'list',
                        height: 275,
                        hidden: true,
                        id: 'pList',
                        width: 140,
                        itemTpl: [
                            '<div>{name}</div>'
                        ],
                        store: 'MyStore1'
                    },
                    {
                        xtype: 'list',
                        height: 315,
                        hidden: true,
                        id: 'dList',
                        width: 308,
                        itemTpl: [
                            '<div>{actions}</div>'
                        ],
                        store: 'DepositStore'
                    },
                    {
                        xtype: 'list',
                        height: 278,
                        hidden: true,
                        id: 'tList',
                        itemId: 'mylist5',
                        width: 233,
                        itemTpl: [
                            '<div>{actions}</div>'
                        ],
                        store: 'TransferStore'
                    },
                    {
                        xtype: 'list',
                        height: 278,
                        hidden: true,
                        id: 'bList',
                        width: 233,
                        layout: {
                            type: 'vbox'
                        },
                        itemTpl: [
                            '<div>{actions}</div>'
                        ],
                        store: 'BillPayStore'
                    },
                    {
                        xtype: 'list',
                        height: 278,
                        hidden: true,
                        id: 'mList',
                        width: 233,
                        layout: {
                            type: 'vbox'
                        },
                        itemTpl: [
                            '<div>{actions}</div>'
                        ],
                        store: 'MoreStore'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        height: 55,
                        title: '',
                        items: [
                            {
                                xtype: 'button',
                                height: 49,
                                itemId: 'Portfolio',
                                width: 78,
                                text: 'Portfolio'
                            },
                            {
                                xtype: 'button',
                                height: 49,
                                id: 'Deposit',
                                itemId: 'mybutton4',
                                width: 78,
                                text: 'Deposit'
                            },
                            {
                                xtype: 'button',
                                height: 49,
                                id: 'Transfer',
                                itemId: '',
                                width: 78,
                                text: 'Transfer'
                            },
                            {
                                xtype: 'button',
                                height: 49,
                                itemId: 'Deposit',
                                width: 78,
                                text: 'Bill Pay'
                            },
                            {
                                xtype: 'button',
                                height: 49,
                                itemId: 'More',
                                width: 78,
                                text: 'More'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'makeTransfer',
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        height: '',
                        html: '',
                        width: '100%',
                        scrollable: false,
                        title: 'Make a Transfer',
                        layout: {
                            align: 'center',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                align: 'right',
                                id: 'logoutBtn',
                                itemId: 'mybutton5',
                                iconAlign: 'right',
                                text: 'Logout'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        border: '5 10 10 10',
                        id: 'fromField',
                        itemId: '',
                        label: 'From',
                        name: '',
                        placeHolder: 'Select Account'
                    },
                    {
                        xtype: 'textfield',
                        border: '5 10 10 10',
                        disabled: true,
                        id: 'toField',
                        label: 'To',
                        name: '',
                        placeHolder: 'Select Account'
                    },
                    {
                        xtype: 'textfield',
                        border: '5 10 10 10',
                        disabled: true,
                        id: 'amountField',
                        itemId: 'mytextfield2',
                        label: 'Amount',
                        name: '',
                        placeHolder: '$'
                    },
                    {
                        xtype: 'segmentedbutton',
                        left: '30%',
                        width: '32.81%',
                        items: [
                            {
                                xtype: 'button',
                                id: 'oneTimeBtn',
                                left: '',
                                width: '50%',
                                text: 'One Time'
                            },
                            {
                                xtype: 'button',
                                left: '',
                                width: '50%',
                                text: 'Recurring'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        label: 'Type'
                    },
                    {
                        xtype: 'textfield',
                        height: 51,
                        label: 'Initiation Date',
                        labelWrap: true,
                        placeHolder: '9/19/2012'
                    },
                    {
                        xtype: 'spacer',
                        height: 50
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'continueBtn',
                        itemId: 'mybutton3',
                        left: '3%',
                        right: '3%',
                        text: 'Continue'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom'
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'fromPanel',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'textfield',
                                width: 214,
                                label: 'From ',
                                placeHolder: 'Select Account'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton1',
                                width: 46,
                                text: 'All'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton2',
                                width: 134,
                                text: 'Morgan Stanley'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton3',
                                width: 104,
                                text: 'Other Banks'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        height: 2000,
                        id: 'fromList',
                        itemId: '',
                        layout: {
                            type: 'fit'
                        },
                        itemTpl: [
                            '<div></br>{Nickname}          {Balance}</br>{AccountNo}</div>'
                        ],
                        store: 'accounts',
                        grouped: true,
                        pinHeaders: false
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'toPanel',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'textfield',
                                width: 214,
                                label: 'To',
                                placeHolder: 'Select Account'
                            },
                            {
                                xtype: 'button',
                                id: 'CancelBtn',
                                width: 72,
                                text: 'Cancel'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton1',
                                width: 46,
                                text: 'All'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton2',
                                width: 134,
                                text: 'Morgan Stanley'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton3',
                                width: 104,
                                text: 'Other Banks'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        height: 2000,
                        id: 'toList',
                        itemId: 'mylist1',
                        layout: {
                            type: 'fit'
                        },
                        itemTpl: [
                            '<div></br>{Nickname}          {Balance}</br>{AccountNo}</div>'
                        ],
                        store: 'accounts',
                        grouped: true,
                        pinHeaders: false
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'amountPanel',
                layout: {
                    type: 'card'
                },
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'textfield',
                                width: 210,
                                label: 'Amount',
                                placeHolder: '$  5000.00'
                            },
                            {
                                xtype: 'button',
                                text: 'Cancel'
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        height: '5%'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        height: '',
                        title: 'Your Daily limit is $50,000.00'
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                id: 'doneBtn',
                                itemId: 'mybutton20',
                                text: 'Done'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        ui: 'light',
                        items: [
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '1'
                            },
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '2'
                            },
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '3'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        ui: 'light',
                        items: [
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '4'
                            },
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '5'
                            },
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '6'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        ui: 'light',
                        items: [
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '7'
                            },
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '8'
                            },
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '9'
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        ui: 'light',
                        items: [
                            {
                                xtype: 'button',
                                width: '30%',
                                text: ''
                            },
                            {
                                xtype: 'button',
                                width: '30%',
                                text: '0'
                            },
                            {
                                xtype: 'button',
                                ui: 'back',
                                width: '27%',
                                text: 'X'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'repeatPanel',
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'textfield',
                                width: 210,
                                label: 'Repeat',
                                placeHolder: 'Until I Cancel'
                            },
                            {
                                xtype: 'button',
                                text: 'Cancel'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        label: 'Until I Cancel',
                        labelWidth: '80%'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Until Specified Date',
                        labelWidth: '80%'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Until Specified Amount',
                        labelWidth: '80%'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Until Specific # of Transactions',
                        labelWidth: '80%'
                    }
                ]
            },
            {
                xtype: 'panel',
                height: '',
                hidden: true,
                id: 'myCal',
                ui: ''
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'reviewPanel',
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        height: 57,
                        html: '',
                        width: '100%',
                        scrollable: false,
                        title: 'Review Transferrrr',
                        layout: {
                            align: 'center',
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                align: 'right',
                                iconAlign: 'right',
                                text: 'Edit'
                            },
                            {
                                xtype: 'button',
                                text: 'Cancel'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        height: '8%',
                        html: '$1,550,000.00',
                        label: 'From',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Nickname Of Account 1',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '8%',
                        html: '$12,000.00',
                        label: 'To',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Nickname Of Account 2',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '8%',
                        html: '',
                        label: 'Amount',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: '$5,000',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '8%',
                        html: '',
                        label: 'Type',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Recurring',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '8%',
                        html: '',
                        label: 'Every',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Week',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '8%',
                        html: '10/5/2012',
                        label: 'Repeat',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Until Specified Date',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: 46,
                        html: '',
                        left: '',
                        label: 'Initiation Date',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: '9/19/2012',
                        readOnly: true
                    },
                    {
                        xtype: 'spacer',
                        height: '16%'
                    },
                    {
                        xtype: 'spacer',
                        height: '6%'
                    },
                    {
                        xtype: 'button',
                        height: 51,
                        itemId: 'mybutton29',
                        left: '3%',
                        right: '3%',
                        text: 'Submit'
                    }
                ]
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'splashPanel'
            },
            {
                xtype: 'panel',
                hidden: true,
                id: 'confirmPanel',
                items: [
                    {
                        xtype: 'button',
                        height: 49,
                        text: 'Transfer Successfully Submitted'
                    },
                    {
                        xtype: 'textfield',
                        height: '5%',
                        html: '$1,550,000.00',
                        label: 'From',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Nickname Of Account 1',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '5%',
                        html: '$12,000.00',
                        label: 'To',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Nickname Of Account 2',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '5%',
                        html: '',
                        label: 'Amount',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: '$5,000',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '5%',
                        html: '',
                        label: 'Type',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Recurring',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '5%',
                        html: '',
                        label: 'Every',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Week',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        height: '5%',
                        html: '10/5/2012',
                        label: 'Repeat',
                        labelWidth: '33%',
                        name: 'from',
                        placeHolder: 'Until Specified Date',
                        readOnly: true
                    },
                    {
                        xtype: 'spacer',
                        height: '10%'
                    },
                    {
                        xtype: 'button',
                        height: 45,
                        itemId: 'mybutton31',
                        text: 'Make Another Transfer'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onTListItemTap',
                event: 'itemtap',
                delegate: '#tList'
            },
            {
                fn: 'onMybutton31Tap1',
                event: 'tap',
                delegate: '#Portfolio'
            },
            {
                fn: 'onDepositTap',
                event: 'tap',
                delegate: '#Deposit'
            },
            {
                fn: 'onMybutton31Tap111',
                event: 'tap',
                delegate: '#Transfer'
            },
            {
                fn: 'onMybutton31Tap112',
                event: 'tap',
                delegate: '#Deposit'
            },
            {
                fn: 'onMybutton31Tap1121',
                event: 'tap',
                delegate: '#More'
            },
            {
                fn: 'onLogoutBtnTap',
                event: 'tap',
                delegate: '#logoutBtn'
            },
            {
                fn: 'onContinueBtnTap',
                event: 'tap',
                delegate: '#continueBtn'
            },
            {
                fn: 'onMybutton1Tap',
                event: 'tap',
                delegate: '#mybutton1'
            },
            {
                fn: 'onMybutton2Tap',
                event: 'tap',
                delegate: '#mybutton2'
            },
            {
                fn: 'onMybutton3Tap',
                event: 'tap',
                delegate: '#mybutton3'
            },
            {
                fn: 'onFromListItemTap',
                event: 'itemtap',
                delegate: '#fromList'
            },
            {
                fn: 'onMybutton1Tap',
                event: 'tap',
                delegate: '#mybutton1'
            },
            {
                fn: 'onMybutton2Tap',
                event: 'tap',
                delegate: '#mybutton2'
            },
            {
                fn: 'onMybutton3Tap',
                event: 'tap',
                delegate: '#mybutton3'
            },
            {
                fn: 'onToListItemTap',
                event: 'itemtap',
                delegate: '#toList'
            },
            {
                fn: 'onDoneBtnTap',
                event: 'tap',
                delegate: '#doneBtn'
            },
            {
                fn: 'onMybutton29Tap',
                event: 'tap',
                delegate: '#mybutton29'
            },
            {
                fn: 'onMybutton31Tap',
                event: 'tap',
                delegate: '#mybutton31'
            }
        ]
    },

    onTListItemTap: function(dataview, index, target, record, e, options) {
        var temp = record.data.actions;
        if(temp == "Make A Transfer")
        {
            Ext.getCmp('makeTransfer').show();
            Ext.getCmp('homeView').hide();
        }
    },

    onMybutton31Tap1: function(button, e, options) {
        Ext.getCmp('dList').hide();
        Ext.getCmp('pList').show();
        Ext.getCmp('bList').hide();
        Ext.getCmp('mList').hide();
        Ext.getCmp('tList').hide();
    },

    onDepositTap: function(button, e, options) {
        Ext.getCmp('dList').show();
        Ext.getCmp('pList').hide();
        Ext.getCmp('bList').hide();
        Ext.getCmp('mList').hide();
        Ext.getCmp('tList').hide();
    },

    onMybutton31Tap111: function(button, e, options) {
        Ext.getCmp('dList').hide();
        Ext.getCmp('pList').hide();
        Ext.getCmp('bList').hide();
        Ext.getCmp('mList').hide();
        Ext.getCmp('tList').show();
    },

    onMybutton31Tap112: function(button, e, options) {
        Ext.getCmp('dList').hide();
        Ext.getCmp('pList').hide();
        Ext.getCmp('bList').show();
        Ext.getCmp('mList').hide();
        Ext.getCmp('tList').hide();
    },

    onMybutton31Tap1121: function(button, e, options) {
        Ext.getCmp('dList').hide();
        Ext.getCmp('pList').hide();
        Ext.getCmp('bList').hide();
        Ext.getCmp('mList').show();
        Ext.getCmp('tList').hide();
    },

    onLogoutBtnTap: function(button, e, options) {
        Ext.getCmp('makeTransfer').hide();
        Ext.getCmp('homeView').show();
        Ext.getCmp('tList').hide();
    },

    onContinueBtnTap: function(button, e, options) {
        Ext.getCmp('makeTransfer').hide();
        Ext.getCmp('reviewPanel').show();


    },

    onMybutton1Tap: function(button, e, options) {
        Ext.StoreMgr.get('accounts').clearFilter(true);
        Ext.StoreMgr.get('accounts').load();
    },

    onMybutton2Tap: function(button, e, options) {
        Ext.StoreMgr.get('accounts').clearFilter(true);
        Ext.StoreMgr.get('accounts').filter('Bank', 'MS');
    },

    onMybutton3Tap: function(button, e, options) {
        Ext.StoreMgr.get('accounts').clearFilter(true);
        Ext.StoreMgr.get('accounts').filter('Bank', 'other');
    },

    onFromListItemTap: function(dataview, index, target, record, e, options) {
        Ext.getCmp('fromPanel').hide();
        Ext.getCmp('makeTransfer').show();
        Ext.getCmp('toField').enable();
        Ext.getCmp('fromField').setValue(record.data.AccountNo);
    },

    onMybutton1Tap: function(button, e, options) {
        Ext.StoreMgr.get('accounts').clearFilter(true);
        Ext.StoreMgr.get('accounts').load();
    },

    onMybutton2Tap: function(button, e, options) {
        Ext.StoreMgr.get('accounts').clearFilter(true);
        Ext.StoreMgr.get('accounts').filter('Bank', 'MS');
    },

    onMybutton3Tap: function(button, e, options) {
        Ext.StoreMgr.get('accounts').clearFilter(true);
        Ext.StoreMgr.get('accounts').filter('Bank', 'other');
    },

    onToListItemTap: function(dataview, index, target, record, e, options) {
        Ext.getCmp('toPanel').hide();
        Ext.getCmp('makeTransfer').show();
        Ext.getCmp('amountField').enable();
        Ext.getCmp('toField').setValue(record.data.AccountNo);
    },

    onDoneBtnTap: function(button, e, options) {
        Ext.getCmp('amountPanel').hide();
        Ext.getCmp('makeTransfer').show();
        Ext.getCmp('continueBtn').show();

    },

    onMybutton29Tap: function(button, e, options) {
        Ext.getCmp('reviewPanel').hide();
        Ext.getCmp('confirmPanel').show();
    },

    onMybutton31Tap: function(button, e, options) {
        Ext.getCmp('confirmPanel').hide();
        Ext.getCmp('makeTransfer').show();
        Ext.getCmp('continueBtn').hide();
    }

});